### ISSUE TITLE
Change port 5000

### ISSUE THREAD

**Issue by verlaine** [Crapworks/ceph-dash#10]
Hello,

Thanks for the awesome job. 
Is there a way we can change the port number from 5000?

**Comment by verlaine** [comment]
Ok,

I think I got it:
app.run(port=5001,debug=False, host='0.0.0.0')

Is that correct ?

**Comment by Crapworks** [comment]
Hi Verlaine,

yes, you can change the port for the build-in webserver via the ```port``` attribute of the ```run``` function. Anyways, for a live usage scenario, I strongly recommend you to deploy ceph-dash into a WSGI capable webserver.

For more information: http://wsgi.readthedocs.org/en/latest/

Regards,
Christian
