### ISSUE TITLE
how open monitor?

### ISSUE THREAD

**Issue by alex1528** [Crapworks/ceph-dash#19]
./ceph-dash.py 
 Running on http://127.0.0.1:5000/
 Restarting with reloader

how change the ip 127.0.0.1 ?

tks!

**Comment by Crapworks** [comment]
If you want the development server to listen on all interfaces, you can open ```ceph-dash.py``` and change the line

```python
app.run(debug=True)
```
to
```python
app.run(host='0.0.0.0', debug=True)
```

I anyways recommend you to deploy ceph-dash into a WSGI capable webserver like Apache or Nginx

Cheers,
Christian

**Comment by Crapworks** [comment]
No response means usually it works :) So I am closing this.
