### ISSUE TITLE
[Feature request] Storage Utilization per Root (and Pool)

### ISSUE THREAD

**Issue by subsecond** [Crapworks/ceph-dash#20]
I like the simplicity and ease-of-use of ceph-dash a lot. Thanks for the great work and for sharing!

In our Ceph cluster we have several different pools and I'd love to see a bar chart / donut representing the utilization per pool instead of the existing overall storage utilization graph. If you are thinking about implementing something in that direction I'd be willing to support your work by donating to the project.

**Comment by a-nldisr** [comment]
+1 Great feature request for a great dashboard!

**Comment by Crapworks** [comment]
I just had a quick look into it. I am just wondering how you want to see the utilization of several pools, because pools don't have a particular size. They span over the whole cluster. So I am not sure how to visualize that so it makes sense.

**Comment by subsecond** [comment]
Yes, you are right in terms of several pools _can_ share the same OSDs, but they do not necessarily span the whole cluster.
Let me make a simple example here: You have 5 nodes for storage and 3 nodes for backups. Then you might have 2 pools (images and volumes) that span the 5 storage nodes and hence have the same storage utilization and another pool (backups) that spans the 3 backup nodes only. That would look something like the following on the CLI:

```
# ceph df
GLOBAL:
    SIZE     AVAIL     RAW USED     %RAW USED 
    115T      114T         276G          0.23 
POOLS:
    NAME        ID     USED       %USED     MAX AVAIL     OBJECTS 
    images      1      89562M      0.07         9370G       11244 
    volumes     2       2421M         0         9370G         371 
    backups     3           0         0        29792G           0 

```

Now the graph could show three bars:
* The ones for images and volumes would have the same overall capacity.
* The one for backups however shows a different total capacity.

An even more detailed view could be achieved by graphing the output of:

```
# ceph osd df tree
```

But this output can be rather large and therefore it would probably be more confusing than helpful.

I hope that this description helps to gain a better understanding of the use case at hand.

**Comment by Crapworks** [comment]
I see what you mean. But I am still not sure how to visualize that, without creating confusion. 
To take your example, creating three bars like this:

```
images    89G  / 9,3T
volumes   2,4G / 9,3T
backups   0b   / 29T
```
maybe visualized as progress bars, would suggest that you have, in sum, about 19T for volumes and images, which is not the case. Those pools will be full even if the progress bars are only both filled 50%

And the ceph osd df tree seems only to work for newer version. We are currently running Giant and ceph doesn't understand it. So backwards compatibility is also something to take care of.

Cheers

**Comment by richarson** [comment]
It'd be a nice feature to have but I agree with @Crapworks that it could be confusing.

Maybe a donut chart per root instead of per pool? And optionally, each donut could use different colors for each pool inside that root.

**Comment by subsecond** [comment]
I do see @Crapworks point as well. The suggestion of @richarson sounds good and I had a quick look at the implementation possibilities:

```
ceph osd tree
````
is giving us the necessary information on the different roots, their hosts and osds. Especially the osd IDs are important (to store them in an array per root for example)

```
ceph osd df
```
would give us the utilization per osd but as @Crapworks is pointing out, this CLI command was introduced with Hammer only (reference: https://ceph.com/releases/v0-94-hammer-released/). So what do we do with Giant? Suggestions?

**Comment by subsecond** [comment]
Okay, I can answer that one myself:
```
ceph pg dump
````
is our friend (the very last part of the output). The output has to be parsed of course but the command is available in Giant as well as Hammer.

**Comment by richarson** [comment]
@subsecond, giant has:

```
ceph df
GLOBAL:
    SIZE     AVAIL      RAW USED     %RAW USED 
    202T     49207G         154T         76.29 
POOLS:
    NAME              ID     USED       %USED     MAX AVAIL     OBJECTS  
    data              0           0         0        12239G            0 
    metadata          1           0         0        12239G            0 
    rbd               2           8         0        12239G            1 
    volumes           3      37851G     18.24         7149G      5590804 
    images            4        157G      0.08         7149G        20139 
    backups           5      37426G     18.04        12239G     17606809 
[snip]
```

Does it also work in hammer, or only `ceph osd df` does?

**Comment by subsecond** [comment]
`ceph df` works both in Giant and Hammer. But that's useless information if we don't want to start confusing people as pointed out earlier.
So my suggestion is to use a combination of `ceph osd tree` and `ceph pg dump` to get the storage utilization by root instead of pool. What do you think about that?

**Comment by richarson** [comment]
Ah, my mistake, I thought you recommended `ceph osd df` for hammer and something else fo giant.
Upon re-reading I see that wasn't you intention.

**Comment by Crapworks** [comment]
Good Morning,

I was playing around with the pool stuff yesterday. A way of displaying it with less confusion could be something like this:

![example1](https://cloud.githubusercontent.com/assets/1851528/10479880/21c020b0-7267-11e5-9b78-b9a1c7104b7e.png)
![example2](https://cloud.githubusercontent.com/assets/1851528/10479879/21be7c38-7267-11e5-941e-17102f9dd177.png)

Where you can clearly see the overall utilization and on the same bar also the utilization of different pools (there should be a tooltip, hovering over the triangle indicators). Would that be usefull?

Cheers

**Comment by subsecond** [comment]
Hey there! 
Man you are fast.

Let me get that straight: The needle is still showing the storage capacity used in the entire cluster (so all roots, not per root?) and the triangles are showing the usage of the different pools? Did I get that right?
If so, the needle would always point to the last triangle in the graph, correct?

One other thing that is bugging me with aggregating the graph is scale. Let me make an extreme example here: If the storage pool is 10G large and the backup pool is 100 TB large, then the triangle would be at 0% for the storage pool (and possible other pools spanning the same OSDs).

I still vote for separate graphs per root. And then combine it with your suggestion and show a triangle for every pool within that root. That would be amazing!

**Comment by Crapworks** [comment]
It is a bit different (as you can see we're already getting confused about the visualization ;) ).
I can only tell that theoretically, because we only use one pool, spanning across all OSDs. But lets say you have the following:

* 1 Cluster with total: 100TB
* 1 pool(a) across all OSDs: 10TB used.
* 1 pool(b) with maximum 10TB available; 5TB used.
* 1 pool(c) with maximum 1TB available, 1GB used

Let's say for simplicity sake the replication factor is 1. The graph would show the following:
* overall utilization: 15,1 TB of 100TB = 15% (thats where the needle points to)
* pool a: 10TB of 100TB =  10% (first rectangle)
* pool b: 5TB of 10TB = 50% (second rectangle with is higher than the overall one, because the graph is showing percentages)
* pool c: 1GB of 1TB = 0,1% (third triangle)

I hope you understand my logic in this.
My problem with drawing another graph is that this would make it harder to display the whole page on a monitor, which was my initial reason to build this dashboard. so I am looking for a solution that can be integrated without using much space.

Cheers

**Comment by Crapworks** [comment]
And another thing I have to consider: using all the commands you mentioned would result in 3-4 request per refresh to the cluster, compared with 1-2 right now, which would slow the overall speed down on a significant amount, since the refresh timer is 5 seconds (and I want it to be as realtime as possible). During my testing with pools I was using librados ```open_ioctx()``` and ```get_stats()``` functions, which are extremely fast and lightweight.

**Comment by richarson** [comment]
@Crapworks, thanks for the clarification of the graph, that makes sense to me.

Avoiding having several donuts also makes sense, I like this "one look" approach of ceph-dash and that's why I'm using it (in a big monitor where everyone can see it!).

Also, I should have mentioned that `ceph pg dump` produces a json file of 61 MB for me (currently 41 osds in one pool, 273 osds in another pool), and it brings a lot of usless (for this case) information, so using some other method to obtain only the data you need would probably be better.

**Comment by Crapworks** [comment]
Played around with visualization some more (on basis of per pool utilization). Would this be usefull understandable?

![example3](https://cloud.githubusercontent.com/assets/1851528/10514511/666b9bee-734e-11e5-84dc-cd36d760e12b.png)

Are we even still going in the originally requested direction or is there no need for something like this?

Cheers

**Comment by subsecond** [comment]
That is amazing @Crapworks!
And a small detail: This graph also has some similarities with the Ceph logo, so I like it even more than the old capacity graph. Well done!

**Comment by Crapworks** [comment]
Hey guys, there is a new (testing) branch [here](https://github.com/Crapworks/ceph-dash/tree/per_pool_util) were you can check the code out and give it a try. If it is working, please share some screenshots, because as I told you, I only have one pool and it looks kind of boring :)

Cheers

**Comment by subsecond** [comment]
Hey @Crapworks, great job!
Here is a picture of how it looks like on an (almost) fresh install of Ceph Hammer with five pools (2 roots):

![ceph-pools](https://cloud.githubusercontent.com/assets/3658034/10539547/80320498-7400-11e5-9c92-b8855468ac12.png)

Once we will have more data stored, I'll gladly share some new screenshots.
If I might ask for one more favour though: Can you increase the boldness (font-weight) of the font in the hover element a tiny bit? It is really hard to read on low-res TV screen (1280x720) even though it looks elegant.

Next step: You upgrade to Hammer as well :)
* You could stack the graphs sharing the same root then.
* You could show the OSDs that are "most full", like the top 5 or something.
* You could show the IOPS per root/pool and not just overall read/writes

Yeah, yeah, I'll shut up now. Thanks for a job well done! Please provide us with your PayPal/Flattr/... account.

**Comment by Crapworks** [comment]
Well, I will think about you suggestions, although I want to make it configurable what view you choose, an overall cluster view or an per pool view. This for sure will take me significantly more time :) My personal next steps are cleaning up the javascript hell I've created to make things more dynamic.

If you want to donate to the project, you can do that [here](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=5YZHN4U5PRSBW). Although this is not necessary, since I am doing it just for fun.

Cheers

**Comment by subsecond** [comment]
People need to understand that even though a piece software may be open-source and free, it does not mean that enhancements are free of charge as well. I like your spirit but I'm sure you spent quite some time implementing that particular feature. So please understand our donation as a token of appreciation for your work. Thanks a lot and keep on rockin'!

**Comment by Crapworks** [comment]
Thank you very much! I will definitely put it to good use! 
I've adjusted the font weight, but since I am not at work anymore, I can't test it. It should be more readable anyways.

Shall I close this issue?

Cheers

**Comment by subsecond** [comment]
Well deserved. Yes, please go ahead and close this request for enhancement.
Enjoy your weekend! Cheers

**Comment by richarson** [comment]
Looking good!

I was a bit busy so I couldn't comment on this, I'll see if I can give the testing branch a try and share a screenshot.

And if you're going to make it configurable and it's not much work, I'd like the option of showing only per root instead of per pool, as that's more useful to us at work.

Otherwise, it's a very nice improvement, my colleagues really liked those screenshots :)

Plus, what @subsecond said about donations: take it as a "thank you beer" (or whatever beverage you prefer) from us for a great work!

**Comment by richarson** [comment]
OK, here's a screenshot:
![ceph-dash-per_pool_util_1](https://cloud.githubusercontent.com/assets/1638444/10552307/5be65e62-7429-11e5-9a5a-1eac29dc727d.png)

Notice that the % is wrong, one of the pools on the other root shows 36.62 TB / 11.52 TB (316.54 %).

Here's my `ceph df` if it helps narrowing down the problem:

```
GLOBAL:
    SIZE     AVAIL      RAW USED     %RAW USED 
    202T     48331G         155T         76.66 
POOLS:
    NAME              ID     USED       %USED     MAX AVAIL     OBJECTS  
    data              0           0         0        11846G            0   (root sata)
    metadata          1           0         0        11846G            0   (root sata)
    rbd               2           8         0        11846G            1   (root sata)
    volumes           3      38104G     18.40         7089G      5594582   (root ssd)
    images            4        157G      0.08         7089G        20139   (root ssd)
    backups           5      37500G     18.11        11846G     17606049   (root sata)
    vms               6           0         0         7089G            1   (root ssd)
    snaps             9       3464G      1.67        11846G      1956665   (root sata)
    images2           10      6144M         0         7089G          771   (root ssd)
    volumes2          11          0         0         7089G            2   (root ssd)
    backups2          12          0         0        11846G            0   (root sata)
    volumes2-sata     13          0         0        11846G            1   (root sata)
```

Though, that's not accurate either: `((11846 * 7) + (7089 * 5)) / 1024 = 115 TB`

Let me know if I can do anything to debug it.

**Comment by subsecond** [comment]
Hmm, you are right. We are having the same issue.
Apparently, the "MAX AVAIL" column shows the free space within that specific root and not the total initial capacity. This is smart and stupid at the same time and of course not an issue of ceph-dash.
The fix on the other hand is simple enough: Instead of calculating the percentage based on the output, we just use the "%USED" column instead.

So the hover element could display something like:
```
volumes: 18.4% used, 6.93 TB available
```
That would also be the most useful information we can gather from that output. Agreed?

**Comment by subsecond** [comment]
It's even worse than I feared:
```
GLOBAL:
    SIZE     AVAIL     RAW USED     %RAW USED 
    115T      113T        1408G          1.19 
POOLS:
    NAME        ID     USED       %USED     MAX AVAIL     OBJECTS
    images      0      94682M      0.08         8961G       11886
    volumes     1        412G      0.35         8961G       62459
    backups     2           0         0        29792G           0
```
Let's start at the top: `1408 / (115*1024) * 100 = 1.1956%`
So far so good, but that's the total capacity, not respecting replication levels and summing up all the roots and pools. So it's basically zero useful information.

Next, bearing in mind that "MAX AVAIL" is the remaining capacity, respecting replication levels, of the *images* and *volumes* root: `(94682 / 1024 + 412) / 8961 * 100 =  5.6295%`
So what are those 0.08 and 0.35% all about? They are relative to the total cluster capacity (e.g. `412 / (115 * 1024) * 100 = 0.3498%`). Again, zero useful information.

Ceph-dash can only graph information that Ceph is providing. And IMHO Ceph is doing quite a bad job in showing accurate and useful information.

Ideas?

**Comment by subsecond** [comment]
So, further digging revealed the reason(s) for this behaviour:
* A root can span certain OSDs
* A root can have several pools spanning those OSDs
* Another root can span (some / all of) these OSDs as well

Here is why there is no way to get a (static) pool capacity value:
If two roots A and B span the same OSD x, then pools in root A can use capacity on that OSD as well as pools in root B. So basically, the available capacity on that OSD x implies free space for pools in root A *as well as* in root B. This is why it is constantly changing.

Approach:
I suggest that we change the displayed values (and the graph) as follows.
```
volumes: 412G / 9.15TB (4.4% used)
```
Calculation:
* 412G is the actual used capacity in the pool "volumes"
* 9.15TB is calculated by adding the used capacity of that pool with the "MAX AVAIL" value
* Percentage is `used / total * 100`

What do you guys think?

**Comment by Crapworks** [comment]
Hi all,

first of all, my personal opinion:
I don't think that it is a good idea to have two roots spanning over the same osd. I don't even think having two roots over different OSD's is usefull in most cases (except for cache tiering). If it is really needed to seperate the data physically, I would prefer either a (phsysical) seperate ceph cluster or using different cluster in ceph itself (which is supported and more clean that complicated cursh maps).

Anyways, can you explain me your calculation example a bit more? Am I understanding you correct that you want:

```{name}: {bytes_used} / {bytes_used} + {may_avail}``` ?

Cheers

**Comment by subsecond** [comment]
I fully agree with you @Crapworks, it's bad practice to share the same OSDs in different roots. BUT: It's technically possible and hence all the complexity in displaying total capacity.

Yes, I'd love to see the following:
`"{name}: " + {bytes_used} + " / " + ({bytes_used} + {max_avail}) + " (" +  {bytes_used} / ({bytes_used} + {max_avail}) * 100 + "% used)";`

Result would be:
`volumes: 412G / 9.15TB (4.4% used)`

What do you think?

**Comment by Crapworks** [comment]
I've just changed the code and pushed it to the ```per_pool_util``` branch. Looks good for me, the pool utilization is now aligned with the overall cluster utilization. Can you have a look?

**Comment by subsecond** [comment]
Yes, perfect, thanks!
I fear that you will receive support requests on why two pools in the same root do not show the exact same amount of total capacity. The only way around that would be to not only add `bytes_used` of that specific pool, but of all pools in the same root, so:
```
total_capacity_root_1 = bytes_used_pool_1a + bytes_used_pool_1b + ... + max_avail_root_1
total_capacity_root_2 = bytes_used_pool_2a + bytes_used_pool_2b + ... + max_avail_root_2
```

I'm not saying I need that feature, I'm just saying that this will probably raise some questions.
But as you already pointed out, there is no way to gather that information in Giant. And the only other way I could think of is adding `bytes_used` of pools that share the same amount of `max_avail`. This of course comes with a very ugly race condition in case two roots have the exact same `max_avail` at a certain point in time. So not really an option I guess.

Cheers!

**Comment by Crapworks** [comment]
Yeah, I guess that is as good as it gets for < Hammer.
Can you send me the json output of

```# ceph osd df tree --format=json-pretty```

So I can see what information I would get from this?

**Comment by subsecond** [comment]
Sure, I just sent you an email.

**Comment by Crapworks** [comment]
Thanks! I am closing this isse now. Feel free to contact me with further questions or just open a new issue :)

Cheers
