### ISSUE TITLE
Cannot run ceph-dash

### ISSUE THREAD

**Issue by walshy690** [Crapworks/ceph-dash#21]
Good Morning. 

I have use ceph-dash before and it is a brilliant but currently I cannot seem to get it running.

I have my cluster set up and running no problem and have the config.json pointed at my config file but when I type in the command:

<pre>sudo python ceph-dash.py</pre>

I only get this message:

<pre> * Running on http://127.0.0.1:5000/
 * Restarting with reloader</pre>

Any help with this matter is much appreciated.

Walshy

**Comment by Crapworks** [comment]
Well, what do you expect to happen? That is what should happen when you start it on the command line. What problem do you have exactly?

If you are trying to access it from another host and can't reach it, that is because the server by default binds to localhost. See #19 on how to change that

**Comment by walshy690** [comment]
That was the issue I added the IP and it worked. Just to note I am only running a very small personal cluster so it shouldn't cause issues.

Thanks
