### ISSUE TITLE
cannot get timechekMons

### ISSUE THREAD

**Issue by asdfsx** [Crapworks/ceph-dash#22]
I found the format of cluster_status has changed.The format of health parameter has changed.
So monitor status cannot displayed on web page.
The following is the json I received
```json
{u'election_epoch': 1, u'quorum': [0], u'mdsmap': {u'max': 0, u'epoch': 32, u'by_rank': [], u'up': 0, u'in': 0}, 
u'monmap': {u'epoch': 1, u'mons': [{u'name': u'node241', u'rank': 0, u'addr': u'192.168.2.41:6789/0'}], 
u'modified': u'0.000000', u'fsid': u'3b37db44-f401-4409-b3bb-75585d21adfe', u'created': u'0.000000'}, 
u'health': {u'detail': [], 
            u'timechecks': {u'round_status': u'finished', u'epoch': 1, u'round': 0}, 
            u'health': {u'health_services': [{u'mons': [{u'last_updated': u'2015-11-03 12:36:31.878521', u'name': u'node241', u'avail_percent': 96, u'kb_total': 49794300, u'kb_avail': 48088316, u'health': u'HEALTH_OK', u'kb_used': 1705984, u'store_stats': {u'bytes_total': 16770127, u'bytes_log': 2031616, u'last_updated': u'0.000000', u'bytes_misc': 1381005, u'bytes_sst': 13357506}}]}]}, 
            u'overall_status': u'HEALTH_OK', u'summary': []}, 
u'fsid': u'3b37db44-f401-4409-b3bb-75585d21adfe', 
u'quorum_names': [u'node241'], 
u'osdmap': {u'osdmap': {u'full': False, u'nearfull': False, u'num_osds': 5, u'num_up_osds': 5, u'epoch': 190, u'num_in_osds': 5, u'num_remapped_pgs': 0}}, 
u'pgmap': {u'bytes_total': 509773004800, u'num_pgs': 256, u'data_bytes': 269075241, u'bytes_used': 931401728, u'version': 12950, 
           u'pgs_by_state': [{u'count': 256, u'state_name': u'active+clean'}], u'bytes_avail': 508841603072}}  
```

**Comment by Crapworks** [comment]
Hi, can you tell me which version of ceph you are using? I will take a look at this.

Cheers

**Comment by Crapworks** [comment]
And you you please provide me the output of

```ceph status --format=json```

**Comment by asdfsx** [comment]
ceph version 0.94.3 (95cefea9fd9ab740263bf8bb4796fd864d9afe2b) 
```json
{"health":{"health":{"health_services":[{"mons":[{"name":"node241","kb_total":49794300,"kb_used":1718480,"kb_avail":48075820,"avail_percent":96,"last_updated":"2015-11-04 11:52:32.444356","store_stats":{"bytes_total":24125370,"bytes_sst":21748917,"bytes_log":983040,"bytes_misc":1393413,"last_updated":"0.000000"},"health":"HEALTH_OK"}]}]},"timechecks":{"epoch":1,"round":0,"round_status":"finished"},"summary":[],"overall_status":"HEALTH_OK","detail":[]},"fsid":"3b37db44-f401-4409-b3bb-75585d21adfe","election_epoch":1,"quorum":[0],"quorum_names":["node241"],"monmap":{"epoch":1,"fsid":"3b37db44-f401-4409-b3bb-75585d21adfe","modified":"0.000000","created":"0.000000","mons":[{"rank":0,"name":"node241","addr":"192.168.2.41:6789\/0"}]},"osdmap":{"osdmap":{"epoch":190,"num_osds":5,"num_up_osds":5,"num_in_osds":5,"full":false,"nearfull":false,"num_remapped_pgs":0}},"pgmap":{"pgs_by_state":[{"state_name":"active+clean","count":256}],"version":12981,"num_pgs":256,"data_bytes":269075241,"bytes_used":931463168,"bytes_avail":508841541632,"bytes_total":509773004800},"mdsmap":{"epoch":32,"up":0,"in":0,"max":0,"by_rank":[]}}
```

**Comment by asdfsx** [comment]
I forgot to tell you which version I'm using.Sorry for that

**Comment by asdfsx** [comment]
And I wanna know how to collect ceph metrics, and put them into influxdb or elaticsearch

**Comment by stuartbfox** [comment]
Im the same, how are you getting those metrics into graphite or influx in the first place?

ps great project!

**Comment by bladedoyle** [comment]
One suggestion is to run a separate process that uses a REST call to fetch the data from the ceph dashboard app, and then feed that into influxDB using REST call.  I have attached an example of a script to do those things (copied from somewhere and hacked for performance).
[ceph-monitor.py.txt](https://github.com/Crapworks/ceph-dash/files/86815/ceph-monitor.py.txt)

**Comment by Crapworks** [comment]
So, to finally close this issue:
Since ceph dash is not a service/daemon that is constantly running, it can't fetch metrics in a certain interval. The Graphite/InfluxDB integration is only for getting data OUT of those backends.

Do get data INTO them, you have different options:
* build something for yourself like @bladedoyle did
* use a metric agent that does that for you (Diamond, Collectd, etc)
* Use [check_ceph_dash](https://github.com/Crapworks/check_ceph_dash) if you have nagios
* let your imagination flow!

Talking about all the options for metric-gathering and processing would slightly exceed the size of this project. Hope you got some ideas to dig into more by yourself.
