### ISSUE TITLE
Changing ceph-dash.py to listen on 0.0.0.0

### ISSUE THREAD

**Issue by ksingh7** [Crapworks/ceph-dash#24]
Hi whats your thought on changing ceph-dash.py to listen on all ports by default

``` app.run(host='0.0.0.0', debug=True) ```

If we do this by default , will it break anything ? if not should you consider changing this in master branch ?

Thanks for beautiful ceph-dash.

**Comment by Crapworks** [comment]
Done

**Comment by ksingh7** [comment]
Cool Thanks
