### ISSUE TITLE
Error: rados_initialize failed with error code: -22

### ISSUE THREAD

**Issue by prasadpande1990** [Crapworks/ceph-dash#25]
Hi,

I tried to deploy and start ceph-dash on ceph-admin i.e. monitor but I am getting below error when I hit the url. 

![ceph-dash](https://cloud.githubusercontent.com/assets/8678175/11463042/3c5d72ca-96e2-11e5-9455-e95c262908ae.png)

**Comment by Crapworks** [comment]
How does your ```config.json``` look like?
What happens if you just enter ```ceph status``` on the console?

**Comment by Crapworks** [comment]
I am closing this since - no news :)
