### ISSUE TITLE
Read/Write operations on Jewel

### ISSUE THREAD

**Issue by maran** [Crapworks/ceph-dash#28]
On Jewel the operations are split between Read and Write operations so the Ops field is empty. Is there already a way to check which underlying Ceph version is being used? I currently hacked in the operations in but I would like to supply a proper pull request that is backwards compatible.

**Comment by Crapworks** [comment]
Not yet. The status json format was fortunately very stable for quite some time. If it is just one or two fields that changes, I would implement that in the javascript routine that disassembles the json returned from the api, just checking for the presence of certain fields.

It would be cool if you could do that via a pull request! If not, you could provide the json returned from the api and I could figure out how to implement it. Unfortunately my current employer is not running ceph, so my options on testing it would be limited.

Regards,
Christian

**Comment by Crapworks** [comment]
Fixed by #29
