### ISSUE TITLE
No performance metrics

### ISSUE THREAD

**Issue by Lighiche** [Crapworks/ceph-dash#30]
If some one can answer however where do I find more information on this section so I can best layout the graphs?

```
"labels": [ "Read", "Write" ],
 "from": "-2h",
"mode": "byteRate"
```

**FIXED** HAHAHA I'm such a dumb ass. I was editing the wrong config.json -_- I turned up a test instance using flask at first before moving to apache. I was editing the config in the dev dir.

So for anyone that's wondering:
-   make sure the files in dir httpd is serving are owned by that user
-   the way these graphs are pulled in is via the graphite http rest api targets are passed to target
-   http://IPADDR:8080/render?target=servers.ceph-admin.cpu.cpu0.idle
-  So targets should direct be reachable from that url
- it's port 8080 for me since that's where I'm hosting Graphite if you're on port 80 you wont need it or if you're on a different port add that in place

**Thanks Crapworks awesome job btw**

ORIGINAL THREAD:

Hi there, I hate being the one that has to ask but after a few days of fiddling I'm not sure if the issue is with ceph-dash or somewhere else. I can't pull cluster stats, or any stats into ceph-dash

I'm hosting it httpd ssl on centos 7, everything else seems to be functioning normally. For completeness I'll tell you It's a dev Graphite instance specifically for testing this, and a dev icinga2 as well. I can't seem to get anything to pull from graphite, I've tried graphs that I know work like avg(x.x.x.cpu.idle) as a test. 

in config.json I've also tried all of these: 

```
 url": "http://IPADDR:8080",
 url": "http://IPADDR:2003",
 url": "http://IPADDR",
```

Everything else seems to be. Just let me know what else you need from me. Firewalls are turned off and both nodes have full access to each other.

config.json
```
{
    "ceph_config": "/etc/ceph/ceph.conf",
    "graphite": {
        "url": "http://x.x.x.x", // obviously filled in, in my config
        "metrics": [
            {
                "targets": [
                    "avg(servers.ceph-admin.cpu.cpu0.idle)",
                    "avg(monitoring.ceph-mon*.ceph_overall_cluster_status.write_bytes_sec)"
                ],
                "labels": [ "Read", "Write" ],
                "from": "-2h",
                "mode": "byteRate"
            },
            {
                "targets": [
                    "avg(monitoring.ceph-mon*.ceph_overall_cluster_status.op_per_sec)"
                ],
                "labels": [ "IOPS" ],
                "colors": [ "#5bc0de" ],
                "from": "-2h"
            }
        ]
    }
}
```
This is what it looks like for me:

![graphite-vs-ceph-dash](https://cloud.githubusercontent.com/assets/7663736/16263396/14bff734-386c-11e6-8e74-55687f02068a.png)

**Comment by Crapworks** [comment]
So... I am not sure now, can I close it or do are there any questions left?

**Comment by Lighiche** [comment]
Only question is: If someone can answer however where do I find more information on this section so I can best layout the graphs?

"labels": [ "Read", "Write" ],
 "from": "-2h",
"mode": "byteRate"

**Comment by Crapworks** [comment]
*labels*:
Adds a label to the graph. It is an array that it mapped to your specified graphite targets

*from*
Tell graphite the timerange to show metrics. -2h means show the metrics from the last 2 hours

*mode*
How to scale the metrics. "byteRate" formats the data as byte per second and scales accordingly (KB, MB, GB, etc)
