### ISSUE TITLE
Port conflict with ceph-rest-api

### ISSUE THREAD

**Issue by dack** [Crapworks/ceph-dash#37]
Port 5000 is used by both ceph-dash and ceph-rest-api. In addition, the port used by ceph-dash does not appear to be configurable. This prevents running ceph-dash on the same host as ceph-rest-api. I'd suggest using a different default port, as well as adding the option for the user to choose the port.

**Comment by mkkie** [comment]
https://github.com/Crapworks/ceph-dash/issues/23

**Comment by dack** [comment]
Ah, my mistake - should have checked the closed tickets!

Might be worth adding something in the README if it's a common issue.

**Comment by Crapworks** [comment]
I should have done this earlier, indeed. I've put a small paragraph to the quickstart section. Hope that people are going to read it ;)

https://github.com/Crapworks/ceph-dash/blob/master/README.md#quickstart
