### ISSUE TITLE
ceph-dash.py script keeps crashing after a few minutes

### ISSUE THREAD

**Issue by kalpcalp** [Crapworks/ceph-dash#58]
I'm trying to run ceph-dash.py from my mon host, but it crashes every few minutes, and I have to restart it again. Has anyone seen this error before?

version of Ceph I'm using is 11.2.1 (Kraken).

Thanks in advance!

`10.0.203.250 - - [20/Apr/2018 20:55:46] "GET / HTTP/1.1" 200 -
10.0.203.250 - - [20/Apr/2018 20:55:51] "GET / HTTP/1.1" 200 -
10.0.203.250 - - [20/Apr/2018 20:55:56] "GET / HTTP/1.1" 200 -
/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/11.2.1/rpm/el7/BUILD/ceph-11.2.1/src/common/ceph_crypto.cc: In function 'void ceph::crypto::init(CephContext*)' thread 7f99a3e53700 time 2018-04-20 20:56:01.773571
/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/11.2.1/rpm/el7/BUILD/ceph-11.2.1/src/common/ceph_crypto.cc: 77: FAILED assert(crypto_context != __null)`

` ceph version 11.2.1 (e0354f9d3b1eea1d75a7dd487ba8098311be38a7)
 1: (()+0x15b02e) [0x7f99a656b02e]
 2: (()+0x2c2473) [0x7f99a66d2473]
 3: (()+0x26eda5) [0x7f99a667eda5]
 4: (()+0x26b730) [0x7f99a667b730]
 5: (librados::RadosClient::connect()+0x30) [0x7f99a64d9420]
 6: (rados_connect()+0x20) [0x7f99a648c6c0]
 7: (()+0x237c2) [0x7f99aed597c2]
 8: (PyObject_Call()+0x43) [0x7f99bb91b9a3]
 9: (()+0x1b9d6) [0x7f99aed519d6]
 10: (PyObject_Call()+0x43) [0x7f99bb91b9a3]
 11: (PyObject_CallFunctionObjArgs()+0xbc) [0x7f99bb91c29c]
 12: (PyEval_EvalFrameEx()+0x155b) [0x7f99bb9af31b]
 13: (PyEval_EvalCodeEx()+0x7ed) [0x7f99bb9b6efd]
 14: (()+0x7094d) [0x7f99bb94094d]
 15: (PyObject_Call()+0x43) [0x7f99bb91b9a3]
 16: (PyEval_EvalFrameEx()+0x17fd) [0x7f99bb9af5bd]
 17: (PyEval_EvalCodeEx()+0x7ed) [0x7f99bb9b6efd]
 18: (()+0x7094d) [0x7f99bb94094d]
 19: (PyObject_Call()+0x43) [0x7f99bb91b9a3]
 20: (PyEval_EvalFrameEx()+0x17fd) [0x7f99bb9af5bd]
 21: (PyEval_EvalCodeEx()+0x7ed) [0x7f99bb9b6efd]
 22: (()+0x7094d) [0x7f99bb94094d]
 23: (PyObject_Call()+0x43) [0x7f99bb91b9a3]
 24: (PyEval_EvalFrameEx()+0x17fd) [0x7f99bb9af5bd]
 25: (PyEval_EvalFrameEx()+0x67bd) [0x7f99bb9b457d]
 26: (PyEval_EvalFrameEx()+0x67bd) [0x7f99bb9b457d]
 27: (PyEval_EvalFrameEx()+0x67bd) [0x7f99bb9b457d]
 28: (PyEval_EvalCodeEx()+0x7ed) [0x7f99bb9b6efd]
 29: (()+0x70858) [0x7f99bb940858]
 30: (PyObject_Call()+0x43) [0x7f99bb91b9a3]
 31: (()+0x5a995) [0x7f99bb92a995]
 32: (PyObject_Call()+0x43) [0x7f99bb91b9a3]
 33: (()+0xa2ce7) [0x7f99bb972ce7]
 34: (PyObject_Call()+0x43) [0x7f99bb91b9a3]
 35: (PyEval_EvalFrameEx()+0x2336) [0x7f99bb9b00f6]
 36: (PyEval_EvalCodeEx()+0x7ed) [0x7f99bb9b6efd]
 37: (()+0x70858) [0x7f99bb940858]
 38: (PyObject_Call()+0x43) [0x7f99bb91b9a3]
 39: (()+0x5a995) [0x7f99bb92a995]
 40: (PyObject_Call()+0x43) [0x7f99bb91b9a3]
 41: (()+0xa2ce7) [0x7f99bb972ce7]
 42: (PyObject_Call()+0x43) [0x7f99bb91b9a3]
 43: (PyEval_EvalFrameEx()+0x2336) [0x7f99bb9b00f6]
 44: (()+0x661f8) [0x7f99bb9361f8]
 45: (PyEval_EvalFrameEx()+0x1d41) [0x7f99bb9afb01]
 46: (PyEval_EvalCodeEx()+0x7ed) [0x7f99bb9b6efd]
 47: (PyEval_EvalFrameEx()+0x663c) [0x7f99bb9b43fc]
 48: (PyEval_EvalCodeEx()+0x7ed) [0x7f99bb9b6efd]
 49: (PyEval_EvalFrameEx()+0x663c) [0x7f99bb9b43fc]
 50: (PyEval_EvalCodeEx()+0x7ed) [0x7f99bb9b6efd]
 51: (PyEval_EvalFrameEx()+0x663c) [0x7f99bb9b43fc]
 52: (PyEval_EvalCodeEx()+0x7ed) [0x7f99bb9b6efd]
 53: (()+0x70858) [0x7f99bb940858]
 54: (PyObject_Call()+0x43) [0x7f99bb91b9a3]
 55: (()+0x5a995) [0x7f99bb92a995]
 56: (PyObject_Call()+0x43) [0x7f99bb91b9a3]
 57: (PyEval_EvalFrameEx()+0x2336) [0x7f99bb9b00f6]
 58: (PyEval_EvalCodeEx()+0x7ed) [0x7f99bb9b6efd]
 59: (PyEval_EvalFrameEx()+0x663c) [0x7f99bb9b43fc]
 60: (PyEval_EvalCodeEx()+0x7ed) [0x7f99bb9b6efd]
 61: (()+0x70858) [0x7f99bb940858]
 62: (PyObject_Call()+0x43) [0x7f99bb91b9a3]
 63: (()+0x5a995) [0x7f99bb92a995]
 64: (PyObject_Call()+0x43) [0x7f99bb91b9a3]
 65: (()+0xa2947) [0x7f99bb972947]
 66: (()+0xa165f) [0x7f99bb97165f]
 67: (PyObject_Call()+0x43) [0x7f99bb91b9a3]
 68: (PyEval_EvalFrameEx()+0x2336) [0x7f99bb9b00f6]
 69: (PyEval_EvalFrameEx()+0x67bd) [0x7f99bb9b457d]
 70: (PyEval_EvalFrameEx()+0x67bd) [0x7f99bb9b457d]
 71: (PyEval_EvalFrameEx()+0x67bd) [0x7f99bb9b457d]
 72: (PyEval_EvalCodeEx()+0x7ed) [0x7f99bb9b6efd]
 73: (()+0x70858) [0x7f99bb940858]
 74: (PyObject_Call()+0x43) [0x7f99bb91b9a3]
 75: (()+0x5a995) [0x7f99bb92a995]
 76: (PyObject_Call()+0x43) [0x7f99bb91b9a3]
 77: (PyEval_EvalFrameEx()+0x2336) [0x7f99bb9b00f6]
 78: (PyEval_EvalCodeEx()+0x7ed) [0x7f99bb9b6efd]
 79: (PyEval_EvalFrameEx()+0x663c) [0x7f99bb9b43fc]
 80: (PyEval_EvalCodeEx()+0x7ed) [0x7f99bb9b6efd]
 81: (()+0x70858) [0x7f99bb940858]
 82: (PyObject_Call()+0x43) [0x7f99bb91b9a3]
 83: (PyEval_CallObjectWithKeywords()+0x47) [0x7f99bb9ad7b7]
 84: (()+0x1156e2) [0x7f99bb9e56e2]
 85: (()+0x7e25) [0x7f99bb6bbe25]
 86: (clone()+0x6d) [0x7f99bace034d]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.`

**Comment by Crapworks** [comment]
Hi @kalpcalp 

This is an error of your ceph cluster, not from ceph-dash. This can have a multitude of reasons since a ceph cluster is a complex construct. You can probably find some help on the ceph mailing list for this. Do you experience any other problems with you ceph cluster maybe?

Cheers,
Christian

**Comment by Crapworks** [comment]
going to close this, please reopen if the issue persists
