### ISSUE TITLE
TimedOut: error connecting to the cluster

### ISSUE THREAD

**Issue by muhammadhanif** [Crapworks/ceph-dash#59]
I deploy ceph-dash using apache. But i get error:

> [Tue Jun 05 09:44:09.448973 2018] [:error] [pid 27465] ERROR:app:Exception on / [GET]
[Tue Jun 05 09:44:09.449026 2018] [:error] [pid 27465] Traceback (most recent call last):
[Tue Jun 05 09:44:09.449031 2018] [:error] [pid 27465]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
[Tue Jun 05 09:44:09.449034 2018] [:error] [pid 27465]     response = self.full_dispatch_request()
[Tue Jun 05 09:44:09.449036 2018] [:error] [pid 27465]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
[Tue Jun 05 09:44:09.449038 2018] [:error] [pid 27465]     rv = self.handle_user_exception(e)
[Tue Jun 05 09:44:09.449040 2018] [:error] [pid 27465]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
[Tue Jun 05 09:44:09.449056 2018] [:error] [pid 27465]     reraise(exc_type, exc_value, tb)
[Tue Jun 05 09:44:09.449060 2018] [:error] [pid 27465]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
[Tue Jun 05 09:44:09.449062 2018] [:error] [pid 27465]     rv = self.dispatch_request()
[Tue Jun 05 09:44:09.449063 2018] [:error] [pid 27465]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
[Tue Jun 05 09:44:09.449066 2018] [:error] [pid 27465]     return self.view_functions[rule.endpoint](**req.view_args)
[Tue Jun 05 09:44:09.449067 2018] [:error] [pid 27465]   File "/usr/lib/python2.7/site-packages/flask/views.py", line 84, in view
[Tue Jun 05 09:44:09.449069 2018] [:error] [pid 27465]     return self.dispatch_request(*args, **kwargs)
[Tue Jun 05 09:44:09.449071 2018] [:error] [pid 27465]   File "/usr/lib/python2.7/site-packages/flask/views.py", line 149, in dispatch_request
[Tue Jun 05 09:44:09.449073 2018] [:error] [pid 27465]     return meth(*args, **kwargs)
[Tue Jun 05 09:44:09.449092 2018] [:error] [pid 27465]   File "/var/www/html/ceph-dash/contrib/wsgi/../../app/dashboard/views.py", line 112, in get
[Tue Jun 05 09:44:09.449095 2018] [:error] [pid 27465]     with Rados(**self.clusterprop) as cluster:
[Tue Jun 05 09:44:09.449096 2018] [:error] [pid 27465]   File "rados.pyx", line 595, in rados.Rados.__enter__ (rados.c:6875)
[Tue Jun 05 09:44:09.449098 2018] [:error] [pid 27465]   File "rados.pyx", line 785, in rados.Rados.connect (rados.c:8969)
[Tue Jun 05 09:44:09.449100 2018] [:error] [pid 27465] TimedOut: error connecting to the cluster

Could you please give some suggestions?

**Comment by Crapworks** [comment]
Hi @muhammadhanif 

This is an issue connecting to the ceph cluster which is not really realted to ceph-dash. How does your ceph-config looks like and can you issue ceph commands like `ceph status` on the host ceph-dash is running on?

**Comment by Crapworks** [comment]
no response, so I am going to close this
