### ISSUE TITLE
Using in a docker compose file

### ISSUE THREAD

**Issue by Grimdotdotdot** [Crapworks/ceph-dash#60]
When running a docker stack, the environment variables for a docker container have to be placed in a yaml file - something that can't be done (to my knowledge) with the keyring.

Would it be possible to allow the key to be entered as a string?

**Comment by Crapworks** [comment]
Hi @Grimdotdotdot 
when using docker stacks, you can use the `configs` section in your compose file to inject files:
https://docs.docker.com/compose/compose-file/#configs

would that solve your problem?

Cheers,
Christian

**Comment by Grimdotdotdot** [comment]
I'll take a look.
Cheers!

**Comment by Grimdotdotdot** [comment]
Configs is only for the 'config' settings, sadly. However, after a lot of trial and error I finally found the specific combination that both yaml and docker likes:

```version: "3.6"
services:
  container_ceph_monitor:
    image: "crapworks/ceph-dash:latest"
    deploy:
      replicas: 1
    ports:
      - "5000:5000"    
    environment:
      CEPHMONS: 10.0.1.201,10.0.1.202,10.0.1.203
      KEYRING: "[client.admin]\nkey = this_is_my_secret_key==\ncaps mds = \"allow *\"\ncaps mgr = \"allow *\"\ncaps mon = \"allow *\"\ncaps osd = \"allow *\""```

**Comment by Grimdotdotdot** [comment]
In fact, you can get away with just 
```services:
  container_ceph_monitor:
    image: "crapworks/ceph-dash:latest"
    deploy:
      replicas: 1
    ports:
      - "5000:5000"    
    environment:
      CEPHMONS: 10.0.1.1,10.0.1.2,10.0.1.3
      KEYRING: "[client.admin]\nkey = this_is_my_secret_key=="```

**Comment by Crapworks** [comment]
@stryker250 thanks for working on this!
@Grimdotdotdot Is this problem solved for you or are there any other problems?

**Comment by Grimdotdotdot** [comment]
All good for me, thanks!

**Comment by DonaldFoss** [comment]
The docker command line allows environment variables to be set, and there are utilities to parse & convert a string to environment variables and set them. Then there are "secrets" filesystems or tools which could either store or create the keyring file.

BTW, love your email name.

Donald E. Foss

**Comment by DonaldFoss** [comment]
Having service discovery would make that even better so that the cephmons and other services could be dynamic.

Donald E. Foss
