### ISSUE TITLE
metrics are not visible

### ISSUE THREAD

**Issue by javarminator** [Crapworks/ceph-dash#9]
Hi all, 

I've just installed the ceph-dash on a monitor and I copy-pasted the sample configuration file but the metrics section did not show anything on the dashboard 

Help plzzzz
Cheers

**Comment by Crapworks** [comment]
The configuration for graphite is just an example, of course it won't work.
From the ceph-dash readme:
> I've integrated the flot graphing library to make it possible to show some graphs from Graphite in ceph-dash. First of all: ceph-dash does NOT put any data into graphite! You have to do it yourself. 
Do you have a graphite cluster? Do you put teh required data into that cluster? If not, there will be not metrics in ceph-dash.

Regards,
Christian
